Repository CHOP-CGTInformatics/REDCapTidieR, pull requests merged in 2022-11, with the labels that each got.

#69 Preserve REDCap form_name/instrument Order
  NAMESPACE
  R/read_redcap_tidy.R
  tests/testthat/test-read_redcap_tidy.R
Labels: bug

#72 fix read_redcap_tidy() failure with forms argument when project has more than 2 repeating instruments
  R/read_redcap_tidy.R
  tests/testthat/fixtures/my.institution.edu/redcap/api-1bcfaf-POST.csv
  tests/testthat/fixtures/my.institution.edu/redcap/api-4ea52c-POST.csv
  tests/testthat/fixtures/my.institution.edu/redcap/api-5620fa-POST.json
  tests/testthat/fixtures/my.institution.edu/redcap/api-a372aa-POST.csv
  tests/testthat/fixtures/my.institution.edu/redcap/api-a7ee95-POST.csv
  tests/testthat/fixtures/my.institution.edu/redcap/api-cf925b-POST.csv
  tests/testthat/fixtures/my.institution.edu/redcap/api-d019a4-POST.csv
  tests/testthat/test-read_redcap_tidy.R
Labels: bug

#77 Fix extract_* Bug
  R/extract_table.R
  inst/testdata/db_data_classic.RDS
  inst/testdata/db_data_classic_norepeat.RDS
  inst/testdata/db_data_long.RDS
  inst/testdata/db_data_long_noarms.RDS
  inst/testdata/db_data_long_norepeat.RDS
  inst/testdata/db_metadata_classic.RDS
  inst/testdata/db_metadata_classic_norepeat.RDS
  inst/testdata/db_metadata_long.RDS
  inst/testdata/db_metadata_long_noarms.RDS
  inst/testdata/db_metadata_long_norepeat.RDS
  inst/testdata/linked_arms_long.RDS
  inst/testdata/linked_arms_long_noarms.RDS
  inst/testdata/linked_arms_long_norepeat.RDS
  inst/testdata/redcaptidier_longitudinal_db.RDS
  tests/testthat/test-extract_table.R
Labels: bug

#76 Enable Exposure of Survey Fields
  R/clean_redcap.R
  R/clean_redcap_long.R
  R/read_redcap_tidy.R
  docs/404.html
  docs/LICENSE-text.html
  docs/LICENSE.html
  docs/authors.html
  docs/index.html
  docs/pkgdown.yml
  docs/reference/add_partial_keys.html
  docs/reference/clean_redcap.html
  docs/reference/clean_redcap_long.html
  docs/reference/index.html
  docs/reference/link_arms.html
  docs/reference/read_redcap_tidy.html
  docs/sitemap.xml
  man/read_redcap_tidy.Rd
  tests/testthat/fixtures/create-httptest-mock.R
  tests/testthat/fixtures/my.institution.edu/redcap/api-09010e-POST.csv
  tests/testthat/fixtures/my.institution.edu/redcap/api-0efc24-POST.csv
  tests/testthat/fixtures/my.institution.edu/redcap/api-1bcfaf-POST.csv
  tests/testthat/fixtures/my.institution.edu/redcap/api-535b2e-POST.csv
  tests/testthat/fixtures/my.institution.edu/redcap/api-7be96b-POST.csv
  tests/testthat/fixtures/my.institution.edu/redcap/api-a372aa-POST.csv
  tests/testthat/fixtures/my.institution.edu/redcap/api-b113bd-POST.csv
  tests/testthat/test-read_redcap_tidy.R
  vignettes/REDCapTidieR/0/my.institution.edu/redcap/api-0bc81e-POST.csv
  vignettes/longitudinal_redcap/0/my.institution.edu/redcap/api-690f41-POST.csv
Labels: bug, enhancement

#79 Fix repeating id form bug
  R/read_redcap_tidy.R
  inst/httptest/redact.R
  inst/misc/fake_credentials.csv
  tests/testthat/fixtures/create-httptest-mock.R
  tests/testthat/fixtures/my.institution.edu/redcap/api-167271-POST.csv
  tests/testthat/fixtures/my.institution.edu/redcap/api-39a3e8-POST.csv
  tests/testthat/fixtures/my.institution.edu/redcap/api-6c6a70-POST.csv
  tests/testthat/fixtures/my.institution.edu/redcap/api-875e05-POST.csv
  tests/testthat/fixtures/my.institution.edu/redcap/api-cf4e0b-POST.csv
  tests/testthat/fixtures/my.institution.edu/redcap/api-d838b7-POST.json
  tests/testthat/fixtures/my.institution.edu/redcap/api-ffd040-POST.json
  tests/testthat/fixtures/my.institution.edu/redcap/api-fff6ba-POST.csv
  tests/testthat/helper.R
  tests/testthat/test-read_redcap_tidy.R
Labels: bug

#80 Improve preprocessing of field and option labels
  NAMESPACE
  R/read_redcap_tidy.R
  R/utils.R
  inst/testdata/db_data_classic.RDS
  inst/testdata/db_data_classic_norepeat.RDS
  inst/testdata/db_data_long.RDS
  inst/testdata/db_data_long_noarms.RDS
  inst/testdata/db_data_long_norepeat.RDS
  inst/testdata/db_metadata_classic.RDS
  inst/testdata/db_metadata_classic_norepeat.RDS
  inst/testdata/db_metadata_long.RDS
  inst/testdata/db_metadata_long_noarms.RDS
  inst/testdata/db_metadata_long_norepeat.RDS
  inst/testdata/linked_arms_long.RDS
  inst/testdata/linked_arms_long_noarms.RDS
  inst/testdata/linked_arms_long_norepeat.RDS
  inst/testdata/redcaptidier_longitudinal_db.RDS
  man/checkbox_appender.Rd
  man/get_record_id_field.Rd
  man/strip_html_field_embedding.Rd
  man/update_field_names.Rd
  tests/testthat/test-read_redcap_tidy.R
  tests/testthat/test-utils.R
Labels: enhancement

#84 make na_percent 0-100
  R/read_redcap_tidy.R
  tests/testthat/test-read_redcap_tidy.R
Labels: bug

#83 add to `make_labelled()` vignette
  R/labelled.R
  _pkgdown.yml
  docs/pkgdown.yml
  docs/reference/index.html
  man/format-helpers.Rd
  man/make_labelled.Rd
  vignettes/REDCapTidieR.Rmd
Labels: enhancement

#81 Implement labelling w/ updated functionality
  DESCRIPTION
  NAMESPACE
  R/checks.R
  R/labelled.R
  _pkgdown.yml
  docs/pkgdown.yml
  docs/reference/index.html
  docs/sitemap.xml
  man/check_req_labelled_fields.Rd
  man/check_req_labelled_metadata_fields.Rd
  man/format-helpers.Rd
  man/make_labelled.Rd
  man/resolve_formatter.Rd
  renv.lock
  tests/testthat/test-checks.R
  tests/testthat/test-labelled.R
  vignettes/REDCapTidieR.Rmd
Labels: enhancement

#88 Update vignettes
  README.Rmd
  _pkgdown.yml
  inst/httptest/redact.R
  inst/httptest/start-vignette.R
  inst/misc/fake_credentials.csv
  vignettes/REDCapTidieR.Rmd
  vignettes/bind-tables.gif
  vignettes/diving_deeper.Rmd
  vignettes/diving_deeper/0/my.institution.edu/redcap/api-089340-POST.csv
  vignettes/diving_deeper/0/my.institution.edu/redcap/api-0bc81e-POST.csv
  vignettes/diving_deeper/0/my.institution.edu/redcap/api-179bc8-POST.csv
  vignettes/diving_deeper/0/my.institution.edu/redcap/api-3ddbb9-POST.csv
  vignettes/diving_deeper/0/my.institution.edu/redcap/api-6fb904-POST.csv
  vignettes/diving_deeper/0/my.institution.edu/redcap/api-702b49-POST.csv
  vignettes/diving_deeper/0/my.institution.edu/redcap/api-aa9c93-POST.csv
  vignettes/diving_deeper/0/my.institution.edu/redcap/api-c79777-POST.json
  vignettes/diving_deeper/0/my.institution.edu/redcap/api-d99473-POST.csv
  vignettes/diving_deeper/0/my.institution.edu/redcap/api-df97b6-POST.json
  vignettes/diving_deeper/0/my.institution.edu/redcap/api-ef3694-POST.csv
  vignettes/diving_deeper/0/my.institution.edu/redcap/api-f0257a-POST.json
  vignettes/heroes-information-redcap-form.png
  vignettes/labelled-supertibble.png
  vignettes/longitudinal_redcap.Rmd
  vignettes/longitudinal_redcap/0/my.institution.edu/redcap/api-690f41-POST.csv
  vignettes/longitudinal_redcap/0/my.institution.edu/redcap/api-8fcfba-POST.csv
  vignettes/longitudinal_redcap/0/my.institution.edu/redcap/api-b452b5-POST.json
  vignettes/longitudinal_redcap/0/my.institution.edu/redcap/api-bad5b3-POST.csv
  vignettes/longitudinal_redcap/0/my.institution.edu/redcap/api-e0ebd0-POST.csv
  vignettes/viewer-heroes-information.gif
  vignettes/viewer-metadata.gif
  vignettes/viewer-super-hero-powers.gif
  vignettes/viewer-supertibble.gif
Labels: enhancement

#97 Survey bug fix
  R/clean_redcap.R
  R/clean_redcap_long.R
  R/labelled.R
  tests/testthat/fixtures/my.institution.edu/redcap/api-875e05-POST.csv
  tests/testthat/fixtures/my.institution.edu/redcap/api-cf4e0b-POST.csv
  tests/testthat/fixtures/my.institution.edu/redcap/api-ffd040-POST.json
  tests/testthat/fixtures/my.institution.edu/redcap/api-fff6ba-POST.csv
  tests/testthat/test-import_redcap.R
  tests/testthat/test-labelled.R
Labels: bug

#98 NA Percentage Style Change
  DESCRIPTION
  NAMESPACE
  R/import_redcap.R
Labels: enhancement
