Repository CHOP-CGTInformatics/REDCapTidieR, pull requests merged in 2022-10, with the labels that each got.

#42 Enable renv CI Cacheing
  .github/workflows/R-CMD-check.yaml
  renv/profiles/dev/renv.lock
Labels: documentation, enhancement

#43 Add parameter to load specific forms in read_redcap_tidy
  DESCRIPTION
  NAMESPACE
  R/checks.R
  R/read_redcap_tidy.R
  man/check_forms_exist.Rd
  man/read_redcap_tidy.Rd
  tests/testthat/test-checks.R
  tests/testthat/test-read_redcap_tidy.R
Labels: enhancement

#41 block/sparse matrix terminology
  .github/workflows/R-CMD-check.yaml
  .github/workflows/pkgdown.yaml
  .github/workflows/test-coverage.yaml
  DESCRIPTION
  R/read_redcap_tidy.R
  vignettes/REDCapTidieR.Rmd
Labels: safe to test

#45 Implement httptest in tests and vignettes
  .github/pull_request_template.md
  .github/workflows/R-CMD-check.yaml
  .github/workflows/pkgdown.yaml
  .github/workflows/test-coverage.yaml
  DESCRIPTION
  inst/httptest/redact.R
  inst/httptest/start-vignette.R
  inst/misc/fake_credentials.csv
  renv.lock
  tests/testthat/fixtures/create-httptest-mock.R
  tests/testthat/fixtures/my.institution.edu/redcap/api-1bcfaf-POST.csv
  tests/testthat/fixtures/my.institution.edu/redcap/api-3f97b1-POST.csv
  tests/testthat/fixtures/my.institution.edu/redcap/api-542e7d-POST.csv
  tests/testthat/fixtures/my.institution.edu/redcap/api-5620fa-POST.json
  tests/testthat/fixtures/my.institution.edu/redcap/api-5b2ec1-POST.csv
  tests/testthat/fixtures/my.institution.edu/redcap/api-71ec82-POST.csv
  tests/testthat/fixtures/my.institution.edu/redcap/api-a372aa-POST.csv
  tests/testthat/fixtures/my.institution.edu/redcap/api-a3f4d8-POST.json
  tests/testthat/fixtures/my.institution.edu/redcap/api-b061ca-POST.json
  tests/testthat/fixtures/my.institution.edu/redcap/api-cf4a3f-POST.csv
  tests/testthat/fixtures/my.institution.edu/redcap/api-fdb0e0-POST.csv
  tests/testthat/fixtures/my.institution.edu/redcap/api-fe1c68-POST.csv
  tests/testthat/helper.R
  tests/testthat/test-read_redcap_tidy.R
  vignettes/REDCapTidieR.Rmd
  vignettes/REDCapTidieR/0/my.institution.edu/redcap/api-179bc8-POST.csv
  vignettes/REDCapTidieR/0/my.institution.edu/redcap/api-c79777-POST.json
  vignettes/longitudinal_redcap.Rmd
  vignettes/longitudinal_redcap/0/my.institution.edu/redcap/api-4efae2-POST.csv
  vignettes/longitudinal_redcap/0/my.institution.edu/redcap/api-b452b5-POST.json
  vignettes/longitudinal_redcap/0/my.institution.edu/redcap/api-e0cff7-POST.csv
  vignettes/longitudinal_redcap/0/my.institution.edu/redcap/api-e0ebd0-POST.csv
  vignettes/longitudinal_redcap/0/my.institution.edu/redcap/api-f7cb9f-POST.csv
Labels: enhancement, safe to test

#51 Fix bug causing NAs when first form in project is not requested
  NAMESPACE
  R/read_redcap_tidy.R
  man/get_output_fields.Rd
  tests/testthat/fixtures/create-httptest-mock.R
  tests/testthat/fixtures/my.institution.edu/redcap/api-d019a4-POST.csv
  tests/testthat/test-checks.R
  tests/testthat/test-read_redcap_tidy.R
  tests/testthat/test-utils.R
Labels: bug

#49 check_repeat_nonrepeat Function Optimization
  NAMESPACE
  R/checks.R
  man/check_repeat_and_nonrepeat.Rd
  tests/testthat/test-checks.R
Labels: bug, enhancement

#54 Fix bug removing checkbox fields
  NAMESPACE
  R/read_redcap_tidy.R
  R/utils.R
  man/get_fields_to_drop.Rd
  man/get_output_fields.Rd
  tests/testthat/test-read_redcap_tidy.R
Labels: bug

#60 Fix tidyselect warnings
  .github/workflows/R-CMD-check.yaml
  .github/workflows/pkgdown.yaml
  .github/workflows/test-coverage.yaml
  R/checks.R
  R/clean_redcap.R
  R/clean_redcap_long.R
  R/extract_table.R
  R/utils.R
  renv.lock
Labels: bug

#59 refactor multi_choice_to_labels
  NAMESPACE
  R/utils.R
  man/parse_labels.Rd
  tests/testthat/test-utils.R
Labels: bug, enhancement

#62 Cli implementation
  NAMESPACE
  R/checks.R
  R/extract_table.R
  R/utils.R
  tests/testthat/test-checks.R
  tests/testthat/test-extract_table.R
  tests/testthat/test-read_redcap_tidy.R
  tests/testthat/test-utils.R
Labels: enhancement
