Repository CHOP-CGTInformatics/REDCapTidieR, pull requests merged in 2023-02, with the labels that each got.

#122 Lint in test suite
  DESCRIPTION
  tests/testthat/test-lint-free.R
Labels: enhancement

#119 Wrap `REDCapR` API calls with custom error handling
  NAMESPACE
  R/read_redcap.R
  R/utils.R
  man/try_redcapr.Rd
  tests/testthat/test-utils.R
Labels: enhancement

#118 Warn when duplicate field labels are detected
  NAMESPACE
  R/checks.R
  R/utils.R
  inst/testdata/db_data_classic.RDS
  inst/testdata/db_metadata_classic.RDS
  inst/testdata/redcaptidier_longitudinal_db.RDS
  man/check_parsed_labels.Rd
  man/parse_labels.Rd
  tests/testthat/fixtures/my.institution.edu/redcap/api-535b2e-POST.csv
  tests/testthat/fixtures/my.institution.edu/redcap/api-5620fa-POST.json
  tests/testthat/fixtures/my.institution.edu/redcap/api-95ddd0-POST.R
  tests/testthat/test-checks.R
  tests/testthat/test-read_redcap.R
  tests/testthat/test-utils.R
Labels: bug

#123 Improved `read_redcap()` warnings for databases with access restrictions
  NAMESPACE
  R/checks.R
  inst/httptest/redact.R
  inst/misc/fake_credentials.csv
  tests/testthat/fixtures/create-httptest-mock.R
  tests/testthat/fixtures/my.institution.edu/redcap/api-352902-POST.json
  tests/testthat/fixtures/my.institution.edu/redcap/api-36bd61-POST.csv
  tests/testthat/fixtures/my.institution.edu/redcap/api-82f254-POST.csv
  tests/testthat/fixtures/my.institution.edu/redcap/api-95ddd0-POST.R
  tests/testthat/fixtures/my.institution.edu/redcap/api-cc5db2-POST.csv
  tests/testthat/helper.R
  tests/testthat/test-checks.R
  tests/testthat/test-read_redcap.R
Labels: enhancement

#125 Unexpected Warning Capture and Message for try_redcapr
  DESCRIPTION
  NAMESPACE
  R/utils.R
  tests/testthat/test-utils.R
Labels: bug

#129 Remove whitespace after comma in `parse_labels()`
  DESCRIPTION
  R/utils.R
  tests/testthat/test-utils.R
Labels: bug

#126 Repeating Events Support
  DESCRIPTION
  NAMESPACE
  R/checks.R
  R/clean_redcap.R
  R/clean_redcap_long.R
  R/data.R
  R/labelled.R
  R/read_redcap.R
  R/utils.R
  REDCapTidieR.Rproj
  inst/httptest/redact.R
  inst/misc/fake_credentials.csv
  man/add_partial_keys.Rd
  man/create_repeat_instance_vars.Rd
  man/db_has_repeat_forms.Rd
  man/superheroes_supertbl.Rd
  renv.lock
  tests/testthat/fixtures/create-httptest-mock.R
  tests/testthat/fixtures/my.institution.edu/redcap/api-551ace-POST.csv
  tests/testthat/fixtures/my.institution.edu/redcap/api-59f7d4-POST.csv
  tests/testthat/fixtures/my.institution.edu/redcap/api-62c34a-POST.csv
  tests/testthat/fixtures/my.institution.edu/redcap/api-7abb50-POST.csv
  tests/testthat/fixtures/my.institution.edu/redcap/api-892595-POST.csv
  tests/testthat/fixtures/my.institution.edu/redcap/api-95ddd0-POST.R
  tests/testthat/fixtures/my.institution.edu/redcap/api-c6fa10-POST.csv
  tests/testthat/fixtures/my.institution.edu/redcap/api-d09168-POST.csv
  tests/testthat/fixtures/my.institution.edu/redcap/api-d33cf7-POST.csv
  tests/testthat/fixtures/my.institution.edu/redcap/api-ed7aa8-POST.json
  tests/testthat/fixtures/my.institution.edu/redcap/api-ff2c79-POST.json
  tests/testthat/helper.R
  tests/testthat/test-checks.R
  tests/testthat/test-clean_redcap.R
  tests/testthat/test-clean_redcap_long.R
  tests/testthat/test-labelled.R
  tests/testthat/test-read_redcap.R
  tests/testthat/test-utils.R
  vignettes/REDCapTidieR.Rmd
  vignettes/REDCapTidieR/0/my.institution.edu/redcap/api-160502-POST.csv
  vignettes/diving_deeper.Rmd
  vignettes/diving_deeper/0/my.institution.edu/redcap/api-160502-POST.csv
  vignettes/diving_deeper/0/my.institution.edu/redcap/api-535b2e-POST.csv
  vignettes/diving_deeper/0/my.institution.edu/redcap/api-d9e8e1-POST.csv
  vignettes/glossary.Rmd
Labels: enhancement

#131 Improve mock updating
  .Rbuildignore
  DESCRIPTION
  R/dev_utils.R
  inst/httptest/redact.R
  inst/httptest/start-vignette.R
  man/get_credentials.Rd
  renv.lock
  renv/settings.dcf
  tests/testthat/fixtures/create-httptest-mock.R
  tests/testthat/fixtures/my.institution.edu/redcap/api-59f7d4-POST.csv
  tests/testthat/fixtures/my.institution.edu/redcap/api-7abb50-POST.csv
  tests/testthat/fixtures/my.institution.edu/redcap/api-95ddd0-POST.R
  tests/testthat/fixtures/my.institution.edu/redcap/api-c6fa10-POST.csv
  tests/testthat/fixtures/my.institution.edu/redcap/api-d33cf7-POST.csv
  tests/testthat/fixtures/my.institution.edu/redcap/api-ff2c79-POST.json
  tests/testthat/helper.R
  tests/testthat/test-deprecated.R
  tests/testthat/test-read_redcap.R
  tests/testthat/test-utils.R
  updating-mocks.md
  vignettes/REDCapTidieR.Rmd
  vignettes/REDCapTidieR/0/my.institution.edu/redcap/api-160502-POST.csv
  vignettes/diving_deeper.Rmd
  vignettes/diving_deeper/0/my.institution.edu/redcap/api-160502-POST.csv
  vignettes/diving_deeper/0/my.institution.edu/redcap/api-535b2e-POST.csv
  vignettes/diving_deeper/0/my.institution.edu/redcap/api-5620fa-POST.json
  vignettes/diving_deeper/0/my.institution.edu/redcap/api-d9e8e1-POST.csv
Labels: documentation, enhancement

#133 Improve create repeat instance vars
  DESCRIPTION
  R/utils.R
Labels: enhancement

#135 Consolidate `parse_labels()` errors
  DESCRIPTION
  R/utils.R
  tests/testthat/test-utils.R
Labels: enhancement
