Repository CHOP-CGTInformatics/REDCapTidieR, pull requests merged in 2024-09, with the labels that each got.

#201 Mixed Structure Data Loss Bug Resolution
  NEWS.md
  R/clean_redcap_long.R
  tests/testthat/test-clean_redcap_long.R
Labels: bug

#202 Update REDCapR to 1.2.0, update guess_max to Inf
  DESCRIPTION
  R/read_redcap.R
  man/read_redcap.Rd
Labels: bug, enhancement

#203 Update link_arms, Add event_name to redcap_events Output in Longitudinal Supertibbles
  NAMESPACE
  NEWS.md
  R/REDCapTidieR-package.R
  R/read_redcap.R
  R/utils.R
  tests/testthat/test-utils.R
Labels: enhancement

#208 Proposal: a vignette about labelled vectors
  pkgdown/_pkgdown.yml
  tests/testthat/_snaps/write.md
  tests/testthat/test-utils.R
  vignettes/articles/images/labelled_approaches.png
  vignettes/articles/labelled.Rmd
Labels: documentation
